Add control command ./adbhoney_sh <start|stop|restart|status>

diff --git a/bin/adbhoney_sh b/bin/adbhoney_sh
--- a/bin/adbhoney_sh
+++ b/bin/adbhoney_sh
@@ -1,10 +1,5 @@
 #!/bin/bash
 
-ADB_VIRTUAL_ENV_DEFAULT=adbh_env
-COWRIE_VIRTUAL_ENV="$(config_get COWRIE_VIRTUAL_ENV)";
-
-script_dir=$(dirname "$(readlink -f "$0")")
-
 adbhoney_directory() {
     if [[ "$0" = /* ]]
     then
@@ -14,6 +9,26 @@ adbhoney_directory() {
     fi
     ADBHONEYDIR=$(cd ${ADBHONEYDIR} && pwd -P 2>/dev/null || pwd)
 }
+
+adbhoney_directory $0
+config_dir=${ADBHONEYDIR}/etc
+config_file_name=${config_dir}/adbhoney-launch.cfg
+
+script_dir=$(dirname "$(readlink -f "$0")")
+
+config_read_file() {
+    (grep -E "^${2}=" -m 1 "${1}" 2>/dev/null || echo "VAR=__UNDEFINED__") | head -n 1 | cut -d '=' -f 2-;
+}
+
+config_get() {
+    val="$(config_read_file ${config_file_name} "${1}")";
+    if [ "${val}" = "__UNDEFINED__" ]; then
+        val="$(config_read_file ${config_file_name}.base "${1}")";
+    fi
+    printf -- "%s" "${val}";
+}
+
+ADB_VIRTUAL_ENV="$(config_get ADB_VIRTUAL_ENV)";
 
 activate_venv() {
     # Activate Python virtual environment
@@ -31,14 +46,14 @@ adbhoney_status() {
     PID=$(cat ${PIDFILE} 2>/dev/null || echo "")
     if [ -n "$PID" ]; then
         if ps -p "$PID" 2>&1 >/dev/null; then
-            echo "adbhoney is running (PID: ${PID})."
+            echo "ADBhoneypot is running (PID: ${PID})."
         else
-            echo "adbhoney is not running (PID: ${PID})."
+            echo "ADBhoneypot is not running (PID: ${PID})."
             echo "Removing stale PID file"
             rm -f ${PIDFILE}
         fi
     else
-        echo "adbhoney is not running."
+        echo "ADBhoneypot is not running."
     fi
 }
 
@@ -46,9 +61,16 @@ adbhoney_start() {
     # Start ADBhoney
     PID=$(cat ${PIDFILE} 2>/dev/null || echo -n "")
     if [ -z "$PID" ]; then
-        echo "Starting adbhoney ..."
-        cd ${script_dir} && cd ..
-        nohup python adbhoney.py &>/dev/null & echo $! > ${ADBHONEYDIR}/${PIDFILE}
+        echo "Starting ADBhoneypot ..."
+        if [ ! -z "$VIRTUAL_ENV" ]; then
+            echo 2>&1 "Using activated Python virtual environment \"$VIRTUAL_ENV\""
+            nohup python ${ADBHONEYDIR}/adbhoney.py &>/dev/null & echo $! > ${ADBHONEYDIR}/${PIDFILE}
+        elif activate_venv "$ADB_VIRTUAL_ENV"; then
+            nohup python ${ADBHONEYDIR}/adbhoney.py &>/dev/null & echo $! > ${ADBHONEYDIR}/${PIDFILE}
+            echo 2>&1 "ADBhoneypot is started successfully."
+        else
+            echo 2>&1 "Can't activate virtual environment \"$ADB_VIRTUAL_ENV\"."
+        fi
     fi
 }
 
@@ -56,7 +78,7 @@ adbhoney_stop() {
     # Stop ADBhoney
     PID=$(cat ${PIDFILE} 2>/dev/null || echo -n "")
     if [ -n "$PID" ]; then
-        echo -n "Stopping adbhoney..."
+        echo -n "Stopping ADBhoneypot..."
         if kill -TERM $PID; then
             ((t = 60))
             while ((t > 1)); do
@@ -77,7 +99,7 @@ adbhoney_stop() {
             rm -f ${PIDFILE}
         fi
     else
-        echo "adbhoney is not running."
+        echo "ADBhoneypot is not running."
     fi
 }
 
@@ -97,7 +119,7 @@ fi
 
 adbhoney_directory $0
 cd ${ADBHONEYDIR}
-PIDFILE=var/run/adbhoney.pid
+PIDFILE=adbhoney.pid
 set -e
 
 key=$1
